---
title: "Superfriends Book Club"
subtitle: "`r params$year` Wrapped"
output:
  html_document:
    fig_height: 8
    toc: true
    toc_depth: 2
    toc_float:
      collapsed: false
      smooth_scroll: false
params:
  year: 2025
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  message = FALSE
)
library(readr)
library(plyr)
library(dplyr)
library(tidyr)
library(plotly)
library(kableExtra)
library(knitr)
library(forcats)
library(glue)
```

```{r generate-meta-data}
bookmaker_info <- data.frame(
  bookmaker = as.ordered(c(
    "<i>Guest</i>",
    "<i>Other</i>",
    "<i>Overall</i>",
    "Amanda",
    "Ben",
    "Hannah",
    "Healy",
    "Julia",
    "Katherine",
    "Kevin",
    "Ryan",
    "Sam"
  )),
  color = c(
    "#242424",
    "#ADADAD",
    "#ADADAD",
    "#1f78bf",
    "#b2df8a",
    "#e31a1c",
    "#ff6d01",
    "#ffff99",
    "#cab2d6",
    "#33a02c",
    "#a6cee3",
    "#6a3d9a"
  ),
  pair = c(
    NA,
    NA,
    NA,
    "Ben",
    "Amanda",
    "Kevin",
    "Sam",
    "Ryan",
    "Julia",
    "Hannah",
    "Julia",
    "Healy"
  )
)
bookmaker_info$pair <- ordered(
  bookmaker_info$pair,
  levels = levels(bookmaker_info$bookmaker)
)
bookmaker_info$pair_name <- with(bookmaker_info, {
  paste(pmin(bookmaker, pair), "&", pmax(bookmaker, pair))
})
guest_factor <- bookmaker_info$bookmaker[1]
other_factor <- bookmaker_info$bookmaker[2]
overall_factor <- bookmaker_info$bookmaker[3]
```
```{r generate-ratings}
meta_data <- read_csv(
  "data/SF Book Club Ratings - Meta.csv",
  show_col_types = FALSE
) %>%
  select(-Link) %>%
  rename(
    goodreads_rating = Rating,
    book = Book,
    publish_year = Year,
    pages = Pages,
    genre = Genre,
    gender = `Author Gender`
  ) %>%
  mutate(
    book = gsub(":.*", "", book),  # Remove subtitles
    genre = as.factor(genre),
    gender = factor(
      gender,
      c("M", "F", "N", "O"),
      c("Male", "Female", "Non-binary", "Other")
    ) %>% replace_na("Other"),
    gender = fct_lump_n(gender, 2)  # Keep most common 2, rest as Other
  )

raw_ratings <- read_csv(
  "data/SF Book Club Ratings - Ratings.csv",
  show_col_types = FALSE
) %>%
  select(all_of(c(
    "Healy's Recap",
    "Book Club Date",
    "Bookmaker",
    "Book",
    "Amanda",
    "Ben",
    "Hannah",
    "Healy",
    "Julia",
    "Katherine",
    "Kevin",
    "Ryan",
    "Sam",
    "Guest1",
    "Guest1 Name"
  ))) %>%
  rename(
    recap = `Healy's Recap`,
    date = `Book Club Date`,
    bookmaker = Bookmaker,
    book = Book
  ) %>%
  mutate(
    date = as.Date(date, format = "%m/%d/%Y"),
    year = as.integer(format(date, "%Y")),
    book = gsub(":.*", "", book)  # Remove subtitles
  )

guest_ratings <- raw_ratings %>%
  select(c("date", "Guest1", "Guest1 Name")) %>%
  drop_na() %>%
  pivot_wider(
    id_cols = "date",
    names_from = "Guest1 Name",
    values_from = "Guest1"
  )

ratings <- raw_ratings %>%
  select(-c(recap, Guest1, "Guest1 Name")) %>%
  left_join(guest_ratings, by = "date") %>%
  pivot_longer(
    -c(year, date, bookmaker, book),
    names_to = "rater",
    values_to = "rating"
  ) %>%
  drop_na() %>%
  filter(year <= params$year) %>%
  left_join(meta_data, by = "book") %>%
  mutate(
    current = year == params$year,
    bookmaker = case_when(
      !(bookmaker %in% bookmaker_info$bookmaker) ~ "<i>Guest</i>",
      .default = bookmaker
    )
  )

meta_data <- meta_data %>%
  left_join(
    select(raw_ratings, book, year, recap),
    by = "book"
  ) %>%
  filter(year <= params$year)

ratings$bookmaker <- ordered(
  ratings$bookmaker,
  levels = bookmaker_info$bookmaker
)
ratings$rater <- ordered(ratings$rater, levels = bookmaker_info$bookmaker)

book_to_maker <- ratings %>%
  select(book, bookmaker) %>%
  distinct()
```
```{r make-summaries}
get_ratings_summary <- function(group) {
  all_summary <- ratings %>%
    group_by_at(group) %>%
    dplyr::summarise(
      average = mean(rating),
      stdev = sd(rating),
      n = n(),
      book_count = n_distinct(book),
      books = paste0(sort(unique(book)), collapse = "<br>")
    ) %>%
    mutate(timeframe = "all")
  current_summary <- ratings %>%
    filter(current) %>%
    group_by_at(group) %>%
    dplyr::summarise(
      average = mean(rating),
      stdev = sd(rating),
      n = n(),
      book_count = n_distinct(book),
      books = paste0(sort(unique(book)), collapse = "<br>")
    ) %>%
    mutate(timeframe = "current")
  previous_summary <- ratings %>%
    filter(!current) %>%
    group_by_at(group) %>%
    dplyr::summarise(
      average = mean(rating),
      stdev = sd(rating),
      n = n(),
      book_count = n_distinct(book),
      books = paste0(sort(unique(book)), collapse = "<br>")
    ) %>%
    mutate(timeframe = "previous")
  bind_rows(all_summary, current_summary, previous_summary)
}

books <- get_ratings_summary("book") %>%
  join(book_to_maker, by = "book") %>%
  join(
    select(raw_ratings, book, year, recap),
    by = "book"
  ) %>%
  group_by(timeframe) %>%
  mutate(
    grp_like = cut(average, 2, c("disliked", "liked")),
    grp_cons = cut(stdev, 2, c("Universally", "Tenatatively"))
  ) %>%
  ungroup()

bookmakers <- get_ratings_summary("bookmaker") |>
  filter(rater != "Guest") |>
  left_join(
    books |>
      arrange(desc(average)) |>
      group_by(bookmaker, timeframe) |>
      summarise(
        book_averages = paste0(
          book, ": ",
          format(round(average, 2), nsmall = 2),
          collapse = "<br>"
        )
      ),
    by = c("bookmaker", "timeframe")
  ) |>
  left_join(
    books |>
      arrange(desc(stdev)) |>
      group_by(bookmaker, timeframe) |>
      summarise(
        book_stdevs = paste0(
          book, ": ",
          format(round(stdev, 2), nsmall = 2),
          collapse = "<br>"
        )
      ),
    by = c("bookmaker", "timeframe")
  )

rater_books_ranked <- bind_rows(
  mutate(ratings, timeframe = "all"),
  mutate(ratings, timeframe = if_else(current, "current", "previous"))
) |>
  select(rater, book, rating, timeframe) |>
  group_by(rater, timeframe) |>
  mutate(
    least_favorite = rating == min(rating),
    favorite = rating == max(rating)
  ) |>
  filter(least_favorite | favorite) |>
  group_by(rater, timeframe) |>
  summarise(
    favorite_books = paste0(
      "<b>Favorites: (rating=", max(rating), ")</b><br>",
      paste0(book[favorite], collapse = "<br>")
    ),
    least_favorite_books = paste0(
      "<b>Least favorites: (rating=", min(rating), ")</b><br>",
      paste0(book[!favorite], collapse = "<br>")
    ),
  ) |>
  unite(
    "ranked_books",
    c(favorite_books, least_favorite_books),
    sep = "<br><br>",
    remove = TRUE
  )

raters <- get_ratings_summary("rater") |>
  filter(rater != "Guest") |>
  left_join(
    rater_books_ranked,
    by = c("rater", "timeframe")
  )

raters_bookmakers <- get_ratings_summary(c("rater", "bookmaker")) %>%
  filter(
    !is.na(rater),
    timeframe == "all",
    bookmaker != guest_factor
  ) %>%
  select(rater, bookmaker, average) %>%
  pivot_wider(names_from = bookmaker, values_from = average) %>%
  as.data.frame()
row.names(raters_bookmakers) <- raters_bookmakers$rater
raters_bookmakers$rater <- NULL

ratings_mat <- ratings %>%
  filter(
    !is.na(rater),
    rater %in% raters$rater[raters$n > 5]
  ) %>%
  select(book, rater, rating) %>%
  pivot_wider(names_from = rater, values_from = rating) %>%
  as.data.frame()
row.names(ratings_mat) <- ratings_mat$book
ratings_mat <- select(ratings_mat, -book)

cors <- cor(ratings_mat, use = "pairwise.complete.obs")
cor.mtest <- function(mat, ...) {
    mat <- as.matrix(mat)
    n <- ncol(mat)
    p.mat<- matrix(NA, n, n)
    diag(p.mat) <- 0
    for (i in 1:(n - 1)) {
        for (j in (i + 1):n) {
            tmp <- cor.test(mat[, i], mat[, j], ...)
            p.mat[i, j] <- p.mat[j, i] <- tmp$p.value
        }
    }
  colnames(p.mat) <- rownames(p.mat) <- colnames(mat)
  p.mat
}
p.mat <- cor.mtest(ratings_mat)

cors_long <- as.data.frame.table(
    cors,
    responseName = "cor",
    stringsAsFactors = FALSE
  ) %>%
  filter(Var1 < Var2) %>%
  mutate(pair_name = paste(Var1, "&", Var2)) %>%
  select(-Var1, -Var2) %>%
  arrange(-cor)
```
```{r generate-results-data}
get_best_worst <- function(timeframe, dataset, metric, type) {
  df <- get(dataset) %>%
    filter(timeframe == !!timeframe) %>%
    drop_na()
  target_value <- ifelse(
    type == "best",
    max(df[metric], na.rm = TRUE),
    min(df[metric], na.rm = TRUE)
  )
  result <- df[df[metric] == target_value, ] %>%
    drop_na(all_of(metric)) %>%
    pull(1)

  paste(result, collapse = " / ")
}

set_result_value <- function(
    value,
    timeframe,
    dataset,
    metric,
    type = NA_character_) {

  new_value <- data.frame(
    timeframe = timeframe,
    dataset = dataset,
    metric = metric,
    type = type,
    value = as.character(value)
  )
  results_df <<- results_df %>%
    rows_upsert(new_value, by = c("timeframe", "dataset", "metric", "type"))
}

get_result_value <- function(
    timeframe,
    dataset,
    metric,
    type) {
  df <- results_df %>%
    filter(
      timeframe == !!timeframe,
      dataset == !!dataset,
      metric == !!metric
    )

  if (is.na(type)) {
    df <- df %>%
      filter(is.na(type))
  } else {
    df <- df %>%
      filter(type == !!type)
  }
  df %>% pull(value)
}

results_df <- expand.grid(
  timeframe = c("current", "all", "previous"),
  dataset = c("books", "raters", "bookmakers"),
  metric = c("average", "stdev"),
  type = c("best", "worst"),
  value = NA_character_,
  stringsAsFactors = FALSE
)

for (i in seq_len(nrow(results_df))) {
  timeframe <- results_df[i, "timeframe"]
  dataset <- results_df[i, "dataset"]
  metric <- results_df[i, "metric"]
  type <- results_df[i, "type"]

  result <- get_best_worst(timeframe, dataset, metric, type)
  set_result_value(result, timeframe, dataset, metric, type)
}

for (timeframe in c("all", "current")) {
  num_ratings <- ifelse(
    timeframe == "all",
    nrow(ratings),
    filter(ratings, year == params$year) %>% nrow()
  )
  set_result_value(num_ratings, timeframe, "summary", "ratings")

  set_result_value(
    nrow(filter(books, timeframe == !!timeframe)),
    timeframe,
    "summary",
    "books"
  )

  if (timeframe == "all") {
    set_result_value(
      filter(bookmakers, timeframe == "all") %>%
        pull(book_count) %>%
        max(),
      timeframe,
      "summary",
      "cycle"
    )
  }

  if(timeframe == "all") {
    start_date <- min(ratings$date)
  } else {
    start_date <- ratings %>%
      filter(year == params$year) %>%
      pull(date) %>%
      min()
  }
  if(format(Sys.Date(), "%Y") == params$year) {
    end_date <- Sys.Date()
  } else {
    end_date <- as.Date(paste(params$year, "12", "31", sep = "-"))
  }
  set_result_value(
    difftime(end_date, start_date, units = "d"),
    timeframe,
    "summary",
    "days_since"
  )
}

set_result_value(
  cors_long[[which.max(cors_long$cor), "pair_name"]],
  "all",
  "cors",
  "pairwise",
  "max"
)
set_result_value(
  cors_long[[which.min(cors_long$cor), "pair_name"]],
  "all",
  "cors",
  "pairwise",
  "min"
)
```

```{r make-functions}
make_bar_plot <- function(
  df,
  group,
  metric,
  color = "bookmaker",
  timeframe = "current",
  meta = NA,
  limit = NA
) {
  highlight_current <- (group == "book") & (timeframe == "all")
  hovertemplate <- "%{x:.2f}"

  df <- df %>%
    filter(timeframe == !!timeframe) %>%
    arrange(across(all_of(metric), desc))

  if (highlight_current) {
    df <- df %>%
      mutate(
        book = if_else(
          year == params$year,
          paste0("<span style='color:red'>*", book, "</span>"),
          book
        )
      )
  }

  xaxis_title <- switch(metric,
    "average" = "Avg Rating",
    "std" = "Std. Deviation"
  )

  if (!is.na(limit)) {
    df <- df %>%
      mutate(
        keep = (
          dense_rank(desc(!!sym(metric))) <= limit |
          dense_rank(!!sym(metric)) <= limit |
          year == params$year |
          lag(year) == params$year |
          lead(year) == params$year
        ),
        limit_group = cumsum(keep | (!keep & lag(keep, default = FALSE))),
      )
    df_limit <- df %>%
      group_by(limit_group) %>%
      mutate(book_count = n()) %>%
      filter(!keep, book_count > 1) %>%
      ungroup() %>%
      mutate(limit_group = as.numeric(factor(limit_group))) %>%
      group_by(limit_group) %>%
      summarise(
        recap = paste(book, collapse = "<br>"),
        book = paste0(
          "...",
          strrep("\u200B", limit_group[1])
        ),
        bookmaker = other_factor,
        across(all_of(metric), ~ mean(.x))
      ) %>%
      select(-limit_group)

    df <- bind_rows(df_limit, filter(df, keep)) %>%
      arrange(across(all_of(c(metric, group)), desc))
  }

  if (!is.na(meta)) {
    meta <- df[[meta]]
    hovertemplate <- paste0(hovertemplate, "<br>%{meta}")
  }

  p <- plot_ly(
      type="bar",
      y=df[[group]],
      x=df[[metric]],
      color=df[[color]],
      colors = bookmaker_info$color,
      # legendgroup="group1",  # Can't filter to one legend item
      orientation = "h",
      meta = meta,
      hovertemplate = hovertemplate
    ) %>%
    layout(
      yaxis = list(
        categoryorder = "total ascending",
        title = title
      ),
      xaxis = list(title = xaxis_title),
      showlegend = color != group
    ) %>%
    config(displayModeBar = FALSE)
  p
}
```
```{r make-meta-cors}
meta_cors <- ratings %>%
  group_by(rater) %>%
  summarise(
    across(c(publish_year, pages, goodreads_rating), ~ cor(.x, rating)),
  ) %>%
  drop_na() %>%
  bind_rows(
    ratings %>%
      summarise(
        across(c(publish_year, pages, goodreads_rating), ~ cor(.x, rating)),
      ) %>%
      mutate(rater = overall_factor)
  )

# Categorical meta vars
meta_ratings_diffs <- ratings %>%
  bind_rows(mutate(ratings, rater = overall_factor)) %>%
  select(rater, rating, genre, gender) %>%
  pivot_longer(cols = -c(rater, rating)) %>%
  pivot_wider(
    id_cols = rater,
    names_from = value,
    values_from = rating,
    values_fn=mean
  ) %>%
  mutate(  # Do not change these orders without updating elsewhere too
    genre = `Fiction` - `Non-fiction`,
    gender = `Female` - `Male`
  ) %>%
  select(rater, genre, gender)
```
# Summary Data
```{r pull-summary-numbers}
summary_number <- function(metric) {
  list(
    current = get_result_value("current", "summary", metric, NA),
    all = get_result_value("all", "summary", metric, NA)
  )
}
df <- data.frame(
  row.names = c(
    "Current cycle",
    "Books read",
    "Number of ratings",
    "Avg days between meetings"
  ),
  current = c(
    "",
    summary_number("books")$current,
    summary_number("ratings")$current,
    round(
      as.integer(summary_number("days_since")$current) /
        as.integer(summary_number("books")$current),
      1
    )
  ),
  all = c(
    summary_number("cycle")$all,
    summary_number("books")$all,
    summary_number("ratings")$all,
    round(
      as.integer(summary_number("days_since")$all) /
        as.integer(summary_number("books")$all),
      1
    )
  )
)
df %>%
  kable(
    format = "html",
    escape = FALSE,
    booktabs = TRUE,
    col.names = c(params$year, "All")
  ) %>%
  kable_styling()
```
## Books read this year
```{r, results="asis"}
temp <- ratings %>%
  filter(year == params$year) %>%
  select(date, bookmaker, book) %>%
  distinct() %>%
  left_join(select(books, book, recap)) %>%
  distinct() %>%
  arrange(date) %>%
  mutate(
    output = glue("{row_number()}. *{book}*: {recap} ({bookmaker})")
  )
cat(temp$output, sep="\n")
```
```{r analysis-sections, results="asis"}
analysis_sections <- list(
  books = list(
    title = "Books",
    dataset = "books",
    group = "book",
    meta = "recap",
    limits = c(10, NA, 1)
  ),
  bookmakers = list(
    title = "Bookmakers",
    dataset = "bookmakers",
    group = "bookmaker",
    meta = c("book_averages", "book_stdevs")
  ),
  raters = list(
    title = "Raters",
    dataset = "raters",
    group = "rater",
    meta = c("ranked_books", NA),
    section1_title = "Highest / Lowest",
    section1_metrics = c("Highest", "Lowest"),
    section2_title = "Most / Least Variable",
    color_by = "rater"
  )
)

res <- lapply(analysis_sections, function(opts) {
  knit_child(
    "analysis_section.Rmd",
    envir = list2env(opts),
    quiet = TRUE
  )
})

cat(unlist(res), sep = "\n")
```

# Preference Similarity

## Similarity rankings

Most: `r get_result_value("all", "cors", "pairwise", "max")`

Least: `r get_result_value("all", "cors", "pairwise", "min")`

```{r corr-plot}
# TODO: compare this to last year (do the same for all the ones that are "all" only)
# TODO: box or violin plots for all(?) sections
mat <- cors
diag(mat) <- NA

ranking_df <- apply(mat, 1, function(x) {
  names(sort(x, decreasing = TRUE, na.last = NA))
})
ranking_df <- as.data.frame(t(ranking_df))
colnames(ranking_df) <- column_names <- c(
  "Most",
  "2nd",
  "3rd",
  paste0(seq(4, ncol(ranking_df) - 1), "th"),
  "Least"
)

values_df <- as.data.frame(t(apply(mat, 1, function(x) {
  sort(x, decreasing = TRUE, na.last = NA)
})))
color_func <- function(x) {
  scales::col_numeric(
    palette = c("#ef8a62", "#f7f7f7", "#67a9cf"),
    domain = c(-1, 1)
  )(x)
}

final_table <- ranking_df |>
  kable(escape = FALSE) |>
  kable_styling("striped", full_width = FALSE)
for (i in seq_len(ncol(ranking_df))) {
  final_table <- final_table |>
    column_spec(
      i + 1,
      background = color_func(values_df[[i]]),
      color = ifelse(values_df[[i]] > 0.7, "white", "black")
    )
}

final_table
```

## Couple & Sibling Pairs
```{r}
# TODO: Make this a bar plot
df <- cors_long %>%
  filter(pair_name %in% bookmaker_info$pair_name) %>%
  arrange(desc(cor)) %>%
  mutate(cor = scales::label_percent(accuracy=1)(cor))
row.names(df) <- df$Pair
df$Pair <- NULL

df %>%
  kable(col.names = NULL) %>%
  kable_styling(full_width = FALSE)
```

# Meta data
```{r metadata-sections, results="asis"}
metadata_sections <- list(
  pages = list(
    is_categorical = FALSE,
    title = "Book length",
    meta_var = "pages",
    pref_labels = c(
      "Prefers shorter books",
      "Prefers longer books"
    )
  ),
  publish_year = list(
    is_categorical = FALSE,
    title = "Publish year",
    meta_var = "publish_year",
    pref_labels = c(
      "Prefers older books",
      "Prefers newer books"
    )
  ),
  goodreads_rating = list(
    is_categorical = FALSE,
    title = "Goodreads rating",
    meta_var = "goodreads_rating",
    pref_labels = c(
      "Prefers lower rated books",
      "Prefers higher rated books"
    )
  ),
  genre = list(
    is_categorical = TRUE,
    title = "Fiction vs. Non-fiction",
    meta_var = "genre",
    pref_labels = c(
      ifelse(
        # TODO: Fix this
        min(meta_ratings_diffs$genre, na.rm = TRUE) >= 0,
        "No preference",
        "Prefers non-fiction"
      ),
      "Prefers fiction"
    )
  ),
  author_gender = list(
    is_categorical = TRUE,
    title = "Author gender",
    meta_var = "gender",
    distribution_caption = {
      "Other includes non-binary and multiple authors of different genders."
    },
    pref_labels = c(
      "Prefers male authors",
      "Prefers female authors"
    )
  )
)

res <- lapply(metadata_sections, function(opts) {
  knit_child(
    "metadata_section.Rmd",
    envir = list2env(opts),
    quiet = TRUE
  )
})

cat(unlist(res), sep = "\n")
```
