
```{r}
if (is_categorical) {
  cors_df <- meta_ratings_diffs
} else {
  cors_df <- meta_cors
}
if (!exists("distribution_caption")) distribution_caption <- ""
pref_labels <- paste("Prefers", pref_labels)
```

## `r title` {.tabset}

### Distribution
```{r, fig.height=6, fig.cap = distribution_caption}
# TODO: do this programatically (use plotly?)
bin_width <- 100
bin_boundary <- 0

bin_width <- 19
bin_boundary <- 1880

meta_data %>%
  mutate(
    # TODO: Grab just the max number for display (and format if needed)
    bin = cut_width(
      !!as.name(meta_var),
      width = bin_width,
      boundary = bin_boundary
    ),
    timeframe = ifelse(
      year == params$year,
      year,
      paste0("Pre-", params$year)
    )
  ) %>%
  group_by(timeframe, bin) %>%
  arrange(!!meta_var) %>%
  summarise(
    count = n(),
    books = paste(
      paste0(book, " (", !!as.name(meta_var), ")"),
      collapse = "<br>"
    )
  ) %>%
  plot_ly(alpha = 0.6) %>%
  add_bars(
    hovertext = ~books,
    color = ~timeframe,
    x = ~bin,
    y = ~count,
    hovertemplate = paste(
      "<b>%{y} Book(s):</b>",
      "%{hovertext}<extra></extra>",
      sep = "<br>"
    )
  ) %>%
  layout(
    barmode = "stack",
    bargap = 0,
    xaxis = list(title = list(text = "")),
    yaxis = list(title = list(text = ""))
  )

plot_ly(alpha = 0.6) %>%
  add_histogram(
    data = filter(meta_data, year == params$year),
    name = params$year,
    # hovertext = ~book,
    x = ~.data[[meta_var]]
  ) %>%
  add_histogram(
    data = filter(meta_data, year != params$year),
    name = paste0("Pre-", params$year),
    # hovertext = ~book,
    x = ~.data[[meta_var]]
  ) %>%
  layout(
    barmode = "stack",
    xaxis = list(title = list(text = ""))
  )
```

### Preferences
```{r, fig.height=6}
make_bar_plot(cors_df, "rater", meta_var, color = "rater") %>%
  add_annotations(
    text = pref_labels[1],
    xref = "paper",
    yref = "paper",
    x = 0,
    y = -0.06,
    showarrow = FALSE
  ) %>%
  add_annotations(
    text = pref_labels[2],
    xref = "paper",
    yref = "paper",
    x = 1,
    y = -0.06,
    showarrow = FALSE
  )
```